version: "3.9"

services:
  api:
    image: gpspake/fastapi-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --port 8009
    volumes:
      - .:/app
    ports:
      - "8009:8009"
